version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.18.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  trivia:
    image: semtech/mu-javascript-template
    ports:
      - 8889:80
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - /home/dries/Projects/POC/mu-trivia/mirco/trivia-service:/app/
  cron:
    image: semtech/mu-javascript-template
    ports:
      - 8888:80
      - 9229:9229
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - /home/dries/Projects/POC/mu-trivia/mirco/trivia-cron-service:/app/
