(in-package :mu-cl-resources)

(define-resource trivia ()
    :class (s-prefix "vet:Trivia")
    :properties `(  (:type :string ,(s-prefix "vet:type"))
                    (:difficulty :string ,(s-prefix "vet:difficulty"))
                    (:question :string ,(s-prefix "vet:question"))
                    (:correct_answer :string ,(s-prefix "vet:correct_answer")))
    :resource-base (s-url "http://qmino/data/questions/")
    :on-path "trivias")